name: Build for Nehalem

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  VERSION: v3.10.1

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Runner
        uses: step-security/harden-runner@v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout InfluxDB repository (${{ env.VERSION }})
        uses: actions/checkout@v6
        with:
          repository: "influxdata/influxdb"
          ref: ${{ env.VERSION }}
          path: "influxdb"

      - name: Apply patch
        working-directory: influxdb
        run: "git apply ../influxdb-nehalem.patch"

      - name: Check apply patch
        working-directory: influxdb
        run: "git diff"

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: influxdb
          build-args: |
            PBS_DATE=20250106
            PBS_VERSION=3.11.11
            PBS_TARGET=x86_64-unknown-linux-gnu
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true